from __future__ import annotations

import argparse

from rs_core.dataproc.recall_clean import (
    DEFAULT_INPUT_MANIFEST,
    DEFAULT_MIN_ITEM_INTERACTIONS,
    DEFAULT_MIN_USER_INTERACTIONS,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_POSITIVE_RATING_THRESHOLD,
    DEFAULT_SEQUENCE_MAX_LEN,
    DEFAULT_TEST_RATIO,
    DEFAULT_VALID_RATIO,
    build_recall_clean_tables,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build canonical recall-clean tables from Amazon base datasets."
    )
    parser.add_argument(
        "--input-manifest",
        default=DEFAULT_INPUT_MANIFEST,
        help="Manifest generated by download_and_clean_amazon.py.",
    )
    parser.add_argument(
        "--output-dir",
        default=DEFAULT_OUTPUT_DIR,
        help="Directory for canonical recall-clean outputs.",
    )
    parser.add_argument(
        "--positive-rating-threshold",
        type=float,
        default=DEFAULT_POSITIVE_RATING_THRESHOLD,
        help="Rating threshold used for label_binary.",
    )
    parser.add_argument(
        "--min-user-interactions",
        type=int,
        default=DEFAULT_MIN_USER_INTERACTIONS,
        help="Minimum interactions per user after keep-last dedup.",
    )
    parser.add_argument(
        "--min-item-interactions",
        type=int,
        default=DEFAULT_MIN_ITEM_INTERACTIONS,
        help="Minimum interactions per item after keep-last dedup.",
    )
    parser.add_argument(
        "--valid-ratio",
        type=float,
        default=DEFAULT_VALID_RATIO,
        help="Validation ratio for time-based split.",
    )
    parser.add_argument(
        "--test-ratio",
        type=float,
        default=DEFAULT_TEST_RATIO,
        help="Test ratio for time-based split.",
    )
    parser.add_argument(
        "--min-timestamp",
        type=int,
        default=0,
        help="Optional lower-bound timestamp filter in epoch milliseconds.",
    )
    parser.add_argument(
        "--max-reviews-per-category",
        type=int,
        default=0,
        help="Optional cap when ingesting reviews for smoke verification. 0 means no cap.",
    )
    parser.add_argument(
        "--sequence-max-len",
        type=int,
        default=DEFAULT_SEQUENCE_MAX_LEN,
        help="Maximum recent items preserved in user sequence outputs.",
    )
    parser.add_argument(
        "--small-data-all-train-threshold",
        type=int,
        default=0,
        help="When > 0, put all rows into train if filtered interaction count is at or below this threshold.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite an existing recall_clean.sqlite in the output directory.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    outputs = build_recall_clean_tables(
        input_manifest=args.input_manifest,
        output_dir=args.output_dir,
        positive_rating_threshold=args.positive_rating_threshold,
        min_user_interactions=args.min_user_interactions,
        min_item_interactions=args.min_item_interactions,
        valid_ratio=args.valid_ratio,
        test_ratio=args.test_ratio,
        min_timestamp=args.min_timestamp,
        max_reviews_per_category=args.max_reviews_per_category,
        sequence_max_len=args.sequence_max_len,
        small_data_all_train_threshold=args.small_data_all_train_threshold,
        overwrite=args.overwrite,
    )
    print(f"Canonical interactions written to: {outputs['canonical_interactions_path']}")
    print(f"Canonical items written to: {outputs['canonical_items_path']}")
    print(f"User sequences written to: {outputs['user_sequences_path']}")
    print(f"Train user sequences written to: {outputs['train_user_sequences_path']}")
    print(f"Manifest written to: {outputs['manifest_path']}")
    print(f"Stats written to: {outputs['stats_path']}")


if __name__ == "__main__":
    main()
