package com.sinrotic.rs.user.domain.dto;

import java.util.Map;

/**
 * Request body for merging temporary session preferences generated by Agent dialogue.
 */
public record UpdateSessionPreferenceRequestDTO(
        Map<String, Object> activePreferences,
        String lastUserQuery
) {
}
